
services:
  frontend:
    build:
      context: ./frontend
    tty: true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
    command: sh -c "npm install && npm run dev"

    mem_limit: 512m
    cpus: 0.5

  backend:
    build:
      context: ./backend
    tty: true
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev

    mem_limit: 512m
    cpus: 0.5

  db:
    image: postgres:17
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    ports:
      - 1317:80
    depends_on:
      - backend

volumes:
  postgres_data: