# Generated by Django 6.0.5 on 2026-05-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='dairy_date',
            new_name='diary_date',
        ),
    ]
