# Generated by Django 6.0.5 on 2026-05-31 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_rename_dairy_date_diary_diary_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='body',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='diary_date',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='title',
        ),
        migrations.AddField(
            model_name='diary',
            name='memo',
            field=models.TextField(blank=True, max_length=2000, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='diary',
            name='record_date',
            field=models.DateField(default=datetime.date(2026, 6, 1), verbose_name='記録日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=60.0, max_digits=5, verbose_name='体重(kg)'),
            preserve_default=False,
        ),
    ]
