# Generated by Django 6.0.5 on 2026-06-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_diary_body_remove_diary_diary_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('record_date',), name='unique_record_date'),
        ),
    ]
