# Generated by Django 6.0.5 on 2026-06-04 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_diary_user_heightmonthly_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='diary',
            name='unique_record_date',
        ),
        migrations.RemoveConstraint(
            model_name='heightmonthly',
            name='unique_year_month_height',
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('user', 'record_date'), name='unique_user_record_date'),
        ),
        migrations.AddConstraint(
            model_name='heightmonthly',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_year_month_height'),
        ),
    ]
