# Generated by Django 6.0.6 on 2026-06-04 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_remove_diary_unique_record_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heightmonthly',
            name='target_weight',
            field=models.DecimalField(decimal_places=1, default=60.0, max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='目標体重(kg)'),
            preserve_default=False,
        ),
    ]
